services:
  postgres:
    image: postgres:15-alpine
    container_name: auto_ecole_db_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-auto_ecole_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d # Exécution automatique du schéma au démarrage

volumes:
  postgres_data:
